// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package com.team2502.robot2013.commands;

import edu.wpi.first.wpilibj.Timer;

/**
 * The autonomous command for the 2013 competition
 */
public class  AutonomousCommand extends CommandBase {
    public AutonomousCommand() {
        requires(shooter);
		requires(storage);
    }
    
    // Called just before this Command runs the first time
    protected void initialize() {
		
    }
    
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
		shooter.startShooter(); // 0
		Timer.delay(3); // 3
		shootFrisbee(); // 3.3
		Timer.delay(1); // 4.3
		shootFrisbee(); // 4.6
		shooter.stopShooter(); // 4.6
		Timer.delay(10.4); // 15
    }
    
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    
    // Called once after isFinished returns true
    protected void end() {
		storage.retractFrisbee();
		shooter.stopShooter();
    }
    
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
	
	private void shootFrisbee() {
		storage.pushFrisbee();
		Timer.delay(0.3);
		storage.retractFrisbee();
	}
}
